### ISSUE TITLE
Polish "Pending request" screen

### ISSUE THREAD

**Issue by jxom** [paradigmxyz/rivet#15]
> [!IMPORTANT]
> **If you would like to work on this, please comment and we will assign you to the issue.**

---

All of the "Pending request" screens (when you send transaction or sign message/typed data from the Test Dapp) are pretty incomplete. Would be nice to polish the UI a bit to make it look prettier. A similar UI pattern to our **Block Details** screen would be nice, and we can iterate on the UI later to look even better.

A few notes:
- For transaction requests: We should prettify all the possible data in the transaction request,
- For message signing: We should prettify the sender address and message,
- For typed data: For now, maybe we can just put the JSON in a code block, we can iterate on the UI later to look _a lot_ better for structured typed data.

**Comment by ditto-eth** [comment]
ya probably missing something, but I don't see anywhere in the current UI that is "wrapped" since the window isn't resizable and only place it seems to wrap at all is a truncated address? it doesn't seem to be working for me and I'm not sure what needs to be done to wrap it. 

For the typed data, it's already in a pre/code tag so it works fine unless there was going to be a jsonview type thing? I can just send what I have then.
